{% set name = "sphinxcontrib-plantuml" %}
{% set version = "0.31" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fd74752f8ea070e641c3f8a402fccfa1d4a4056e0967b56033d2a76282d9f956

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=1.6

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sphinx-contrib/plantuml/
  summary: 'Sphinx "plantuml" extension'
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
