{% set name = "sphinxcontrib-plantuml" %}
{% set version = "0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib-plantuml-{{ version }}.tar.gz
  sha256: 8975778eed9c142a42ecdc4ecd83132dec0690c035cae788c123750ead526703

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - sphinx >=1.6

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/plantuml/
  summary: 'Sphinx "plantuml" extension'
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
